#!/usr/bin/env python3
"""Generate sources.tex -- the numbering and the printed register.

THE DEFECT THIS EXISTS FOR
--------------------------
Two, and the first is a layout failure that was measured rather than guessed.

\\source{key} originally printed the key itself as a superscript. Keys are
descriptive, so several run to thirty characters, and a superscript is one
unbreakable run: two of them in a row produced a 193pt overfull line, against a
15pt budget. Printing a number instead makes the mark three characters wide and
the class of defect disappears.

The second is staleness. Appendix D lists the sources, and a hand-typed list
beside a machine-read register is two copies of one thing. The list is
generated here from sources.json, so the appendix cannot describe a register it
no longer matches.

Numbering is by order of appearance in sources.json, which is stable across
runs and reviewable as a diff.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "sources.tex"

BANNER = (
    "% GENERATED BY tools/gen_sources.py -- DO NOT EDIT.\n"
    "%\n"
    "% Numbering and the printed register both come from sources.json.\n"
    "% `python3 tools/gen_sources.py --check` fails a stale file.\n"
)

GRADE_NOTE = {
    "strong": "strong",
    "moderate": "moderate",
    "single-source": "\\textbf{one source}",
    "unverified": "\\textcolor{kitwarn}{\\textbf{refused}}",
}


def esc(s: str) -> str:
    for a, b in (("&", "\\&"), ("%", "\\%"), ("#", "\\#"), ("_", "\\_")):
        s = s.replace(a, b)
    return s


def render(sources: dict) -> str:
    keys = [k for k in sources if not k.startswith("$")]
    lines = [BANNER, ""]
    for n, key in enumerate(keys, 1):
        lines.append(f"\\kitsourcenum{{{key}}}{{{n}}}")

    lines.append("")
    lines.append("\\newcommand{\\kitsourcetable}{%")
    # \raggedright, and it is not cosmetic. A justified list of long addresses
    # sets overfull lines that no rewording can fix, because the offending run
    # is somebody else's URL. A reference list nobody reads in order does not
    # owe its right margin anything.
    lines.append("\\begingroup\\raggedright")
    lines.append("\\begin{description}[leftmargin=2.6em, labelwidth=2.2em, "
                 "labelsep=0.4em, font=\\bfseries\\small, itemsep=3pt]")
    for n, key in enumerate(keys, 1):
        meta = sources[key]
        title = esc(str(meta.get("title", key)))
        who = meta.get("author") or meta.get("publisher") or ""
        who = f", {esc(str(who))}" if who else ""
        grade = GRADE_NOTE.get(meta.get("quality", ""), meta.get("quality", ""))
        read = meta.get("read", "")
        url = str(meta.get("url", ""))
        accessed = str(meta.get("accessed", ""))
        # \url breaks a long address at its separators. A generated register
        # of thirty addresses set as plain \ttfamily produced the three worst
        # overfull lines in the book, at 136, 132 and 118pt.
        shown = f"\\url{{{url}}}" if url.startswith("http") else f"\\texttt{{{esc(url)}}}"
        lines.append(f"\\item[{n}.] \\emph{{{title}}}{who}. "
                     f"{{\\small {grade}, read {read}, checked {accessed}}}\\\\")
        lines.append(f"{{\\scriptsize {shown}}}")
    lines.append("\\end{description}\\endgroup}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    sources = json.loads((ROOT / "sources.json").read_text(encoding="utf-8"))
    wanted = render(sources)
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    n = len([k for k in sources if not k.startswith("$")])

    if "--check" in argv:
        if current == wanted:
            print(f"sources.tex is current ({n} sources)")
            return 0
        print("FAIL sources.tex is stale against sources.json.", file=sys.stderr)
        print("     Run: python3 tools/gen_sources.py", file=sys.stderr)
        return 1

    TARGET.write_text(wanted, encoding="utf-8")
    print(f"sources.tex regenerated ({n} sources)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
