#!/usr/bin/env python3
"""Generate structure.tex from manifest.json.

THE DEFECT THIS EXISTS FOR
--------------------------
The part and chapter sequence is the one thing in this repository that would
otherwise live in two places: manifest.json, which the gates read, and
structure.tex, which LaTeX reads. Two copies of a list stay equal only while
somebody remembers to edit both, and the day they diverge both still compile.
The book would then carry a chapter the gates do not check, or check a chapter
the book does not print, and nothing would say so.

So structure.tex is not edited. It is generated here and verified by
check_structure.py --check, which is what CI runs. An edit to the sequence is
an edit to manifest.json followed by `python3 tools/gen_structure.py`.

Stdlib only, deliberately: a generator that needs a dependency installed is a
generator that fails differently on the two machines this book builds on.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "manifest.json"
TARGET = ROOT / "structure.tex"

BANNER = (
    "% GENERATED BY tools/gen_structure.py -- DO NOT EDIT.\n"
    "%\n"
    "% The sequence lives in manifest.json. Edit that, then re-run the\n"
    "% generator. check_structure.py --check fails the build if this file is\n"
    "% stale, so an edit made here is an edit that will be reverted with a\n"
    "% red build attached to it.\n"
)


def render(manifest: dict) -> str:
    out = [BANNER]
    for part in manifest["parts"]:
        out.append("")
        out.append(f"% ---- Part {part['id']}: {part['title']} " + "-" * 20)
        out.append(f"\\part{{{part['title']}}}")
        out.append(f"\\label{{part:{part['label']}}}")
        out.append(f"\\partsubtitle{{{part['subtitle']}}}")
        for ch in part["chapters"]:
            out.append(f"\\include{{chapters/{ch['n']}-{ch['slug']}}}")
    out.append("")
    out.append("% ---- Appendices " + "-" * 32)
    out.append("\\appendix")
    for app in manifest["appendices"]:
        out.append(f"\\include{{chapters/app-{app['slug']}}}")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    wanted = render(manifest)
    check = "--check" in argv

    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if current == wanted:
        print(f"structure.tex is current ({len(wanted.splitlines())} lines)")
        return 0
    if check:
        print("FAIL structure.tex is stale against manifest.json.", file=sys.stderr)
        print("     Run: python3 tools/gen_structure.py", file=sys.stderr)
        return 1
    TARGET.write_text(wanted, encoding="utf-8")
    print(f"structure.tex regenerated ({len(wanted.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
