#!/usr/bin/env python3
"""Measure this repository and write ledger.tex.

THE DEFECT THIS EXISTS FOR
--------------------------
Appendix E prints counts about this book: chapters, drills, sources at each
grade, templates still unfilled. Those are facts about the tree, they change
with every pass, and a count typed into prose is a claim nobody maintains.

This book spends a whole appendix refusing other people's unmaintained counts.
Printing its own from memory would be the same defect with the author's name on
it, so the counts are measured here and reach the page as \val{} references.

REPORTS, NEVER GATES
--------------------
This tool always exits 0. It is a ledger, not a check. There is no defensible
threshold for "enough drills", and a gate that is permanently red teaches the
next person to stop reading the output -- which costs more than the gate was
ever worth.

What IS gated is staleness: --check fails when ledger.tex does not match the
tree, so the book cannot print a number that was true last month.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "ledger.tex"

BANNER = (
    "% GENERATED BY tools/ledger.py -- DO NOT EDIT.\n"
    "%\n"
    "% Every value here is measured from the tree. Edit the tree, then re-run\n"
    "% the tool. `python3 tools/ledger.py --check` fails a stale file.\n"
)


def measure() -> dict[str, str]:
    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    sources = json.loads((ROOT / "sources.json").read_text(encoding="utf-8"))

    chapters = [c for p in manifest["parts"] for c in p["chapters"]]

    # The same file set check_sources.py reads. Two instruments measuring one
    # quantity must agree, or the book prints two numbers that look like one --
    # which is the defect Chapter 10 is about, committed by the tooling.
    prose = sorted((ROOT / "chapters").glob("*.tex")) + sorted(
        (ROOT / "frontmatter").glob("*.tex")
    )
    body = "\n".join(f.read_text(encoding="utf-8") for f in prose)

    src = {k: v for k, v in sources.items() if not k.startswith("$")}
    grades = {}
    for grade in ("strong", "moderate", "single-source", "unverified"):
        grades[grade] = sum(1 for v in src.values() if v.get("quality") == grade)

    # README.md is the index, not a template -- and it contains the word
    # UNFILLED in its own prose, so counting it would report every index as an
    # unfinished template. Found by reading the first run's output rather than
    # by any check.
    templates = sorted(
        f for f in (ROOT / "templates").glob("*.md") if f.name != "README.md"
    )
    unfilled = [t for t in templates if "UNFILLED" in t.read_text(encoding="utf-8")]

    briefs = sorted((ROOT / "drills" / "role-briefs").glob("*.md"))

    # onepagers/card.tex is the preamble the cards share, not a card. Matched on
    # the naming convention rather than excluded by name, so a sixth card counts
    # the day it is written and a second shared file does not. The first run
    # reported six against a README that says five, which is how it was found.
    cards = sorted((ROOT / "onepagers").glob("*-card.tex"))

    # \reported{..}{key} and \reported[single]{..}{key}. Counted by the optional
    # argument rather than by the source's grade: the page is what a reader
    # sees, so the page is what gets counted.
    reported_plain = len(re.findall(r"\\reported\{", body))
    reported_single = len(re.findall(r"\\reported\[single\]\{", body))

    return {
        "parts": str(len(manifest["parts"])),
        "chapters": str(len(chapters)),
        "bankchapters": str(sum(1 for c in chapters if c["kind"] == "bank")),
        "appendices": str(len(manifest["appendices"])),
        "drills": str(len(re.findall(r"\\begin\{drill\}", body))),
        "questions": str(len(re.findall(r"\\begin\{bankq\}", body))),
        "reported": str(reported_plain + reported_single),
        "reportedsingle": str(reported_single),
        "judgements": str(len(re.findall(r"\\judgement\{", body))),
        "sources": str(len(src)),
        "srcstrong": str(grades["strong"]),
        "srcmoderate": str(grades["moderate"]),
        "srcsingle": str(grades["single-source"]),
        "srcrefused": str(grades["unverified"]),
        "templates": str(len(templates)),
        "unfilled": str(len(unfilled)),
        "rolebriefs": str(len(briefs)),
        "cards": str(len(cards)),
        "words": str(len(body.split())),
    }


def render(values: dict[str, str]) -> str:
    lines = [BANNER]
    for key in sorted(values):
        lines.append(f"\\kitledgerval{{{key}}}{{{values[key]}}}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    values = measure()
    wanted = render(values)
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None

    if "--check" in argv:
        if current == wanted:
            print(f"ledger.tex is current ({len(values)} values)")
            return 0
        print("FAIL ledger.tex is stale against the tree.", file=sys.stderr)
        print("     Run: python3 tools/ledger.py", file=sys.stderr)
        return 1

    TARGET.write_text(wanted, encoding="utf-8")
    width = max(len(k) for k in values)
    print("Ledger -- reported, never gated\n")
    for key in sorted(values):
        print(f"  {key:<{width}}  {values[key]}")
    print(f"\nWritten to {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
